### ISSUE TITLE
Relevance judgments for text document retrieval

### ISSUE THREAD

**Issue by Ninashka** [SignalMedia/Signal-1M-Tools#6]
Is there any ground truth / relevance judgments (query-article pairs) available for this data set to be used in evaluating an information retrieval system ( vector space model with a modified TF-IDF term weighting function) ?

**Comment by dyaaalbakour** [comment]
Thanks for your interest in our dataset and for further reaching out to us.

When we released the dataset, we did not have a particular retrieval task in mind. 

We just wanted to release to the community a collection of news articles from a wide range of sources globally. The purpose was to give researchers an idea of what the data really look like for a news search engine. 


Therefore, it seems that this dataset is not suitable for your research. I recommend looking at TREC https://trec.nist.gov/ . Over the years, they ran evaluation initiative of hundreds of retrieval tasks and they created tens of datasets that are potentially useful for your research

Also, you may want to add your annotations/relevance judgments to the dataset and share it with the community. We have actually release a couple of such annotations, e.g. https://research.signal-ai.com/datasets/index.html
